a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaçao?', a.isspace())
print('É um número?',a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?',a.isalnum())
print('Está em maiúscula?',a.isupper())
print('Está em minúscula?',a.islower())
print('Está capitalizada',a.istitle())
